### ISSUE TITLE
Add support for colecovision

### ISSUE THREAD

**Issue by pasnox** [recalbox/recalbox-themes#123]

**Comment by reivaax** [comment]
Plop pasnox, before add systems on the theme list, it's better to wait (or add :D) the support ON recalbox of the system :). For now, colecovision is not added to a futur release...
https://github.com/recalbox/recalbox-os/issues/300

**Comment by paradadf** [comment]
This can definitely be already closed.

**Comment by rockaddicted** [comment]
Thx dude
