### ISSUE TITLE
[Theme

### ISSUE THREAD

**Issue by Laddyacris** [recalbox/recalbox-themes#53]
Il manque un “effet” sur certains logos.
Quand on passe par exemple sur les logos mame, neogeo, on a un effet grossissant quand le logo du thème est séléctionné.
Cet effet n’est pas retrouvé sur les logos (de mémoire( fba libretro, pcengine, pcengineCD et peut etre quelques d’autres je vérifierai)
ça serait bien que ce soit pareil partout, retirer leffet ou le mettre partout

**Comment by reivaax** [comment]
Je vais regarder mais je pense que c'est avant tout une histoire de taille du logo qui donne cet "effet"... Car rien n'a était fait en ce sens dans les réglages du theme... Je vais donc voir pour normaliser la taille des logos afin de "corriger" ça ;).

**Comment by paradadf** [comment]
I think this one can be closed.
